### PR TITLE
add new catfact

### PR DESCRIPTION
**Pull request by aschlot**
Adds a new source for catfacts. related to issue 28

### CODE REVIEW

**Comment by Erisa** [comment]
Not sure why checks are failing, any idea @spotlightishere?
Seems good aside from that.

**Comment by spotlightishere** [comment]
Excellent question to why checks are failing - I'll update the linter to 3.2.0 in hopes that'll fix.

Thank you for the PR, @aschlot!

**Comment by aschlot** [comment]
You're welcome! @spotlightishere I just noticed on Discord that the primary repo is in a Gitlab instance - I am planning on using Yuuki as a baseline for a creation of mine, and would love to try my hand at making the base better. Would you rather me continue PR's here or in the Gitlab instance?

**Comment by Erisa** [comment]
Hi sorry for the confusion! The GitLab instance was only a temporary thing that was reverted when we moved to this github organisation instead of my personal github account - feel free to continue PRs here if you have any! :)
________________________________

**Pull request merged**
