### PR TITLE
actions: Use GITHUB_TOKEN and other fixes

### PR DESCRIPTION
**Pull request by Erisa**
- Use `GITHUB_TOKEN` for ghcr.io pushing (packages GA!!)
- Grammar: image -> image(s)
- Add more caching
- Make the devcontainer support ARM64
- Make the devcontainer finally pull from ghcr.io
- Add `nano` to the devcontainer so I don't lose my mind

### CODE REVIEW

**Comment by Erisa** [comment]
There's no easy way to do a test run of some of these things like pushing (Thankfully the test builds are okay), so just sanity check the yaml changes and let's see what happens.

**Comment by Erisa** [comment]
Pushing in this way seems to work with a different project under the same conditions: https://github.com/Erisa/Cliptok/runs/2890527795
So hopefully should be safe to do.

**Review by spotlightishere — APPROVED** [review]
Looks great, thank you a ton for sorting this out!

**Comment by spotlightishere** [comment]
Actually, an afterthought - could the caching added be enough to close #83?

**Comment by Erisa** [comment]
> Actually, an afterthought - could the caching added be enough to close #83?

All I did here was enable workflow caches in some places where they weren't for some reason. It would still be a good idea to optimise the use of cache with those bundler layer changes. Need to get around to looking at it sometime.

**Pull request merged**
